services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: flavor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  chat-viewer:
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: flavor
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  db_data:
